<?php

// Plugin definition
$plugin = array(
    'title' => t('030 IT - Overviews'),
    'category' => t('030 IT'),
    'icon' => 'overview.png',
    'theme' => 'overview',
    'regions' => array(
        'stage' => t('Stage'),
        'breadcrumb' => t('Breadcrumb'),
        'three_33_first' => t('1/3'),
        'three_33_second' => t('2/3'),
        'three_33_third' => t('3/3'),
        'content_full' => t('Content Full'),
        'two_50_first' => t('1/2'),
        'two_50_second' => t('2/2'),
        'four_first' => t('1/4'),
        'four_second' => t('2/4'),
        'four_third' => t('3/4'),
        'four_fourth' => t('4/4'),
        'slider_01' => t('Slider 1'),
        'slider_02' => t('Slider 2')
    ),
);
