; This file was auto-generated by drush make
core = 7.x

api = 2
projects[] = "drupal"
; Modules
projects[admin_menu][subdir] = "contrib"

projects[backup_migrate][subdir] = "contrib"

projects[ctools][subdir] = "contrib"

projects[devel][subdir] = "contrib"

projects[ds][subdir] = "contrib"

projects[entity][subdir] = "contrib"

projects[field_group][subdir] = "contrib"

projects[field_slideshow][subdir] = "contrib"

projects[features][subdir] = "contrib"

projects[globalredirect][subdir] = "contrib"

projects[media][subdir] = "contrib"

projects[imagecrop][subdir] = "contrib"

projects[imce][subdir] = "contrib"

projects[imce_wysiwyg][subdir] = "contrib"

projects[jquery_update][subdir] = "contrib"

projects[libraries][subdir] = "contrib"

projects[linkit][subdir] = "contrib"

projects[menu_block][subdir] = "contrib"

projects[module_filter][subdir] = "contrib"

projects[references][subdir] = "contrib"

projects[panelizer][subdir] = "contrib"

projects[panels][subdir] = "contrib"

projects[pathauto][subdir] = "contrib"

projects[token][subdir] = "contrib"

projects[views][subdir] = "contrib"

projects[views_slideshow][subdir] = "contrib"

projects[webform][subdir] = "contrib"

projects[wysiwyg][subdir] = "contrib"

; Themes
projects[] = "adaptivetheme"
projects[] = "versatile"
; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = ""
libraries[ckeditor][download][url] = ""
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.jcarousel][download][type] = ""
libraries[jquery.jcarousel][download][url] = ""
libraries[jquery.jcarousel][directory_name] = "jquery.jcarousel"
libraries[jquery.jcarousel][type] = "library"

