<?php

// Plugin definition
$plugin = array(
    'title' => t('030 IT - Nodeview'),
    'category' => t('030 IT'),
    'icon' => 'nodeview.png',
    'theme' => 'nodeview',
    'regions' => array(
        'stage' => t('Stage'),
        'breadcrumb' => t('Breadcrumb'),
        'content_main' => t('Main Content'),
        'sidebar' => t('Sidebar'),
        'three_33_first' => t('1/3'),
        'three_33_second' => t('2/3'),
        'three_33_third' => t('3/3'),
        'four_first' => t('1/4'),
        'four_second' => t('2/4'),
        'four_third' => t('3/4'),
        'four_fourth' => t('4/4'),
        'slider_01' => t('Slider 1')
    ),
);
