<?php

// Plugin definition
$plugin = array(
  'title' => t('Custom Slider - 3 Rows'),
  'category' => t('Slider'),
  'icon' => 'slidethree.png',
  'theme' => 'slidethree',
  'css' => 'slidethree.css',
  'regions' => array(
  	'place_01' => t('1'),
    'place_02' => t('2'),
    'place_03' => t('3'),
	'place_04' => t('4'),
	'place_05' => t('5'),
    'place_06' => t('6'),
    'place_07' => t('7'),
    'place_08' => t('8'),
    'place_09' => t('9'),
    'place_10' => t('10'),
	'place_11' => t('11'),
	'place_12' => t('12'),
    'place_13' => t('13'),
	'place_14' => t('14'),
	'place_15' => t('15'),
    'place_16' => t('16'),
    'place_17' => t('17'),
    'place_18' => t('18'),
    'place_19' => t('19'),
    'place_20' => t('20'),
	'place_21' => t('21'),
	'place_22' => t('22')
   ),
);
