<?php

// Plugin definition
$plugin = array(
  'title' => t('Custom Slider - 1 Row'),
  'category' => t('Slider'),
  'icon' => 'slideone.png',
  'theme' => 'slideone',
  'css' => 'slideone.css',
  'regions' => array(
  	'line_01' => t('1'),
    'line_02' => t('2'),
    'line_03' => t('3'),
	'line_04' => t('4'),
	'line_05' => t('5'),
    'line_06' => t('6'),
    'line_07' => t('7'),
    'line_08' => t('8'),
    'line_09' => t('9'),
    'line_10' => t('10'),
	'line_11' => t('11'),
	'line_12' => t('12'),
    'line_13' => t('13'),
	'line_14' => t('14'),
	'line_15' => t('15'),
    'line_16' => t('16'),
    'line_17' => t('17'),
    'line_18' => t('18'),
    'line_19' => t('19'),
    'line_20' => t('20')
   ),
);
